#undef  runtracmass
#define periodic_ew
#undef  periodic_ns
#undef allow_particle
#undef rhoonly
#undef  relaxation
#define  fixed_bottom_thickness
#undef gotm_call
#define file_output
#define file_output_cdf
#undef file_output_bin
#undef  implicit
